import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic';
import { AddModuleExports } from '../../wasm';

// const WasmComponent = dynamic({
//   loader: async () => {
//     const exports = (await import('../../add.wasm')) as AddModuleExports;
//     const { add_one: addOne } = exports;
//     return () => <div>{addOne(2)}</div>
//   }
// })

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          My WASM Component:
          {/* <WasmComponent />           */}
        </div>
      </main>
    </>
  )
}
